### ISSUE TITLE
Getting extended comment info

### ISSUE THREAD

**Issue by konsumer** [duplys/git-issues#1]
Hi,
I am writing a plugin to integrate git-issues support with [viewgit](http://viewgit.sourceforge.net/). I have got most things figured out, except how to get info about comments, like author and attachments.  Any help you could provide would be most appreciated.

Currently I am just breaking up the filename of the comment XML file, but how do I actually get the file contents to get the tasty infos contained inside?

would you consider adding a `git comment-read HASH` command?

**Comment by konsumer** [comment]
sorry, that should be `git issues comment-read HASH`  I guess the point is that I'd like something that is more future-proof then parsing the XML myself.

**Comment by jwiegley** [comment]
Would you be interesting in adding such a command to suit your need?
