### ISSUE TITLE
git-issues init fails when README isn't found

### ISSUE THREAD

**Issue by osocurioso** [duplys/git-issues#2]
git-issues init fails due to a failed attempt at copying "README" into .gitissues. I guess git-issues should be updated to rather copy the file "README.textile".

**Comment by JasonWoof** [comment]
This appears to have been fixed in this fork: http://github.com/manniche/git-issues

**Comment by mcepl** [comment]
Me too :) https://github.com/jwiegley/git-issues/pull/6
