### ISSUE TITLE
Installation doc?

### ISSUE THREAD

**Issue by pjz** [duplys/git-issues#5]
How about a paragraph on how/where to install this?  You mention 'put a copy in your repo to keep it version-sync'd with your data' but... what kind of implications does that have on $PATH ?  How would that work exactly, given multiple repos each with a potentially different version?

**Comment by jwiegley** [comment]
I have no real guidance to offer, as I don't use this system anymore.  You can install the script anywhere on your PATH that you like.

**Comment by pjz** [comment]
Does anyone use it anymore?  Is there a similar but more popular project I should be looking at?

**Comment by jwiegley** [comment]
I don't even know.  I use Bugzilla and Org-mode myself these days.

**Comment by manniche** [comment]
I still use git-issues. A similar project is fossil (http://fossil-scm.org) or you could try looking at the list at http://dist-bugs.kitenet.net/software/
