### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by sys520084** [duplys/git-issues#7]
my os is Ubuntu 10.04.2 LTS \n \l , I read you readme , but I don't know how to install it.

**Comment by jwiegley** [comment]
Please try asking this on the mailing list

**Comment by sys520084** [comment]
Can you tell me mailing list address.

**Comment by jwiegley** [comment]
Sure, it is here: http://groups.google.com/group/ledger-cli

**Comment by sys520084** [comment]
Oh ，I‘m sorry you know I at China , China government closed this site.

2011/4/23 jwiegley <
reply@reply.github.com>

> Sure, it is here: http://groups.google.com/group/ledger-cli
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jwiegley/git-issues/issues/7#comment_1047019

## 

Hongjian Yu

**Comment by jwiegley** [comment]
Please try, at the command-line, "apt-get install ledger".

**Comment by sys520084** [comment]
I don't know ledger( command-line accounting）, It's a git issues system?

2011/4/23 jwiegley <
reply@reply.github.com>

> Please try, at the command-line, "apt-get install ledger".
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jwiegley/git-issues/issues/7#comment_1047028

## 

Hongjian Yu

**Comment by jwiegley** [comment]
No, it is not.

**Comment by Zearin** [comment]
Holy crap!  I _was_ interested in this project.  I too was wondering how to install it.  

**Then I read this issue.**

This is some of the _worst_ support I’ve ever seen: cold; dismissive; and most especially, it makes me feel like I’d be S.O.L. if I run into any problems.  

I’ll keep an eye on the repo just in case.  I hope I’m wrong, but I’m not holding my breath.

**Comment by jwiegley** [comment]
I didn't realize when I answered that his question was for git-issues!  So many projects, so little time...  I was expecting him to find much better resources on the mailing list, than on this issue tracker.

That said, Zearin, the project is currently not under development by me, so my suggestion is for you to move on to something more actively maintained.

**Comment by Zearin** [comment]
Oh!  Okay…misunderstanding.  That explains a lot.  ☺  

I’m sad to hear the project is in limbo, though.  May I request that you edit the Github project description (and/or the Readme) to alert newcomers?  

(You could also put something like: “looking for someone to take over this project!  Contact me…”)

…

May the Source™ be with you.  Good hacking!

**Comment by jwiegley** [comment]
Done!  Thanks for the suggestion.
